# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Website Title
tagline:          ''
description:      ''
url:              https://yanb514.github.io

author:           Author Lastname
  name:           ''
  url:

paginate:         10

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/yanb514/yanb514.github.io
